export type GroundArmyApiValue = string | number | null | undefined;
export interface GroundArmyResourceStockpileDto { resourceType: GroundArmyApiValue; quantity: number; }
export interface GroundArmyPopulationDto { totalPopulation: number; baseRecruitablePopulation: number; buildingCapacityBonus: number; totalGroundCapacity: number; }
export interface GroundArmyStructureDto { buildingType: GroundArmyApiValue; category: GroundArmyApiValue; level: number; footprint: number; }
export interface GroundArmyUnitSummaryDto { assetType: GroundArmyApiValue; quantity: number; }
export interface GroundArmyOptionDto { assetType: GroundArmyApiValue; requiredBuildingType: GroundArmyApiValue; requiredBuildingLevel: number; requiredPopulationCapacity: number; estimatedDuration: string; cost: readonly GroundArmyResourceStockpileDto[]; currentStock: number; availabilityStatus: string; availabilityReason: string; }
export interface GroundArmyQueueItemDto { orderId: string; assetType: GroundArmyApiValue; quantity: number; sequence: number; status: GroundArmyApiValue; startsAtUtc: string; endsAtUtc: string; isDue: boolean; }
export interface GroundReadinessSummaryDto { structureCount: number; garrisonUnitTypes: number; totalGarrisonQuantity: number; availableOptionCount: number; blockedOptionCount: number; queueItemCount: number; dueQueueItemCount: number; }
export interface GroundActionAvailabilityDto { enqueueSupported: boolean; enqueueActionStatus: string; enqueueActionReason: string; completeDueSupported: boolean; completeDueActionStatus: string; completeDueActionReason: string; }
export interface GroundDiagnosticsDto { requestPlanetId: string | null; ownerCivilizationId: string | null; hasResourceStockpile: boolean; hasPopulationProfile: boolean; notes: readonly string[]; limitations: readonly string[]; }
export interface GroundArmyPlanetContextDto { planetId: string; planetName: string; solarSystemId: string; solarSystemName: string; isOwnedByRequestingCivilization: boolean; ownerCivilizationId: string | null; ownerCivilizationName: string | null; controlStatus: GroundArmyApiValue; resourceStockpile: readonly GroundArmyResourceStockpileDto[]; population: GroundArmyPopulationDto | null; groundStructures: readonly GroundArmyStructureDto[]; garrison: readonly GroundArmyUnitSummaryDto[]; catalog: readonly GroundArmyOptionDto[]; queue: readonly GroundArmyQueueItemDto[]; readinessSummary: GroundReadinessSummaryDto; actionSummary: GroundActionAvailabilityDto; diagnostics: GroundDiagnosticsDto; }
export interface GroundArmyPlanetOptionDto { planetId: string; planetName: string; solarSystemId: string; solarSystemName: string; isOwnedByRequestingCivilization: boolean; }
export interface GroundArmyUiStateDto { civilizationId: string; selectedPlanetId: string | null; knownPlanets: readonly GroundArmyPlanetOptionDto[]; groundArmy: GroundArmyPlanetContextDto | null; errors: readonly string[]; }
export interface GroundArmyUiStateResponse { succeeded: boolean; uiState: GroundArmyUiStateDto | null; errors: readonly string[]; }
