namespace VoidEmpires.Domain.Research;

public static class ResearchCatalog
{
    private static readonly IReadOnlyDictionary<ResearchType, ResearchDefinition> Definitions =
        new Dictionary<ResearchType, ResearchDefinition>
        {
            [ResearchType.PlanetaryEngineering] = new(ResearchType.PlanetaryEngineering, new ResearchCost(0,100,50,0), "planet_capacity", "Ingenieria planetaria", "colonization", "Colonizacion", "colony-growth", "Crecimiento colonial", "Amplia la capacidad planetaria y la preparacion de expansion de colonia.", "Research", "Investigacion", "research.planetary-engineering", "icon.research-planetary-engineering", 10, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["capacity", "colonization", "growth"]),
            [ResearchType.ResourceExtraction] = new(ResearchType.ResourceExtraction, new ResearchCost(0,120,80,0), "resource_output", "Extraccion de recursos", "economy", "Economia", "resource-yield", "Rendimiento economico", "Mejora la produccion planetaria de recursos dentro del modelo economico actual.", "Research", "Investigacion", "research.resource-extraction", "icon.research-resource-extraction", 20, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["economy", "production", "resources"]),
            [ResearchType.EnergySystems] = new(ResearchType.EnergySystems, new ResearchCost(0,100,100,20), "energy_output", "Sistemas energeticos", "energy", "Energia", "research-acceleration", "Aceleracion de laboratorio", "Reduce la duracion de investigacion y prepara futuras reglas energeticas.", "Research", "Investigacion", "research.energy-systems", "icon.research-energy-systems", 30, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["energy", "duration", "research"]),
            [ResearchType.ConstructionAutomation] = new(ResearchType.ConstructionAutomation, new ResearchCost(0,200,150,50), "build_speed", "Automatizacion de construccion", "administration", "Administracion", "construction-acceleration", "Aceleracion industrial", "Acelera la duracion de construccion aceptada por el backend actual.", "Construction", "Construccion", "research.construction-automation", "icon.research-construction-automation", 40, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["construction", "duration", "industry"]),
            [ResearchType.Propulsion] = new(ResearchType.Propulsion, new ResearchCost(0,250,200,75), "fleet_speed", "Propulsion", "logistics", "Logistica", "orbital-readiness", "Preparacion orbital", "Prepara mejoras de movilidad orbital sin habilitar movimiento final en esta build.", "Research", "Investigacion", "research.propulsion", "icon.research-propulsion", 50, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["fleet", "logistics", "mobility"]),
            [ResearchType.ShipWeapons] = new(ResearchType.ShipWeapons, new ResearchCost(0,300,250,50), "weapon_damage", "Armas de nave", "space-military", "Militar espacial", "space-combat-readiness", "Preparacion de combate espacial", "Describe preparacion militar espacial, pero no activa combate real en esta build.", "Research", "Investigacion", "research.ship-weapons", "icon.research-ship-weapons", 60, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["combat", "fleet", "space"]),
            [ResearchType.Shielding] = new(ResearchType.Shielding, new ResearchCost(0,250,300,50), "shield_strength", "Escudos", "defense", "Defensa", "defense-readiness", "Preparacion defensiva", "Prepara mejoras defensivas sin aplicar mitigacion activa en la cabina actual.", "Defenses", "Defensas", "research.shielding", "icon.research-shielding", 70, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["defense", "shield", "readiness"]),
            [ResearchType.Espionage] = new(ResearchType.Espionage, new ResearchCost(0,150,200,100), "intel_strength", "Espionaje", "exploration", "Exploracion", "intel-readiness", "Preparacion de inteligencia", "Aporta metadata de inteligencia sin habilitar misiones, sabotaje ni contraespionaje.", "Espionage", "Espionaje", "research.espionage", "icon.research-espionage", 80, "current-plus-one", "Cada nueva investigacion apunta al nivel actual + 1.", "unbounded", ["SourcePlanet", "ResearchQueueSlot", "ResourceStockpile"], ["intelligence", "espionage", "visibility"])
        };

    public static ResearchDefinition Get(ResearchType type) => Definitions[type];
}
