namespace VoidEmpires.Domain.Buildings;

public static class BuildingCatalog
{
    private static readonly IReadOnlyDictionary<BuildingType, BuildingDefinition> Definitions =
        new Dictionary<BuildingType, BuildingDefinition>
        {
            [BuildingType.CommandCenter] = new(BuildingType.CommandCenter, 1, 20, new ConstructionCost(0, 500, 250, 0), BuildingCategory.Civilian, "Centro de mando", "colony-core", "Nucleo colonial", "Centro principal de capacidad, administracion y desarrollo de colonia.", "PlanetOverview", "Planeta", "building.command-center", "icon.command-center", 10, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre en el planeta."),
            [BuildingType.MetalMine] = new(BuildingType.MetalMine, 1, 5, new ConstructionCost(0, 60, 15, 0), BuildingCategory.Industrial, "Mina de metal", "resource-production", "Produccion minera", "Extraccion primaria de metal para construccion y crecimiento temprano.", "GeneralConstruction", "Construccion", "building.metal-mine", "icon.metal-mine", 20, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.CrystalMine] = new(BuildingType.CrystalMine, 1, 5, new ConstructionCost(0, 50, 40, 0), BuildingCategory.Industrial, "Mina de cristal", "resource-production", "Produccion minera", "Extraccion de cristal para investigacion y construccion avanzada.", "GeneralConstruction", "Construccion", "building.crystal-mine", "icon.crystal-mine", 30, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.GasExtractor] = new(BuildingType.GasExtractor, 1, 6, new ConstructionCost(0, 75, 30, 20), BuildingCategory.Industrial, "Extractor de gas", "resource-production", "Produccion minera", "Extraccion de gas para investigacion y produccion orbital.", "GeneralConstruction", "Construccion", "building.gas-extractor", "icon.gas-extractor", 40, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.SolarPlant] = new(BuildingType.SolarPlant, 1, 4, new ConstructionCost(0, 40, 10, 0), BuildingCategory.Industrial, "Planta solar", "energy-support", "Soporte energetico", "Infraestructura energetica basica para sostener crecimiento industrial.", "GeneralConstruction", "Construccion", "building.solar-plant", "icon.solar-plant", 50, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.ResearchLab] = new(BuildingType.ResearchLab, 1, 12, new ConstructionCost(0, 200, 120, 25), BuildingCategory.Research, "Laboratorio de investigacion", "research-enabler", "Centro de investigacion", "Desbloquea y acelera la preparacion del progreso tecnologico.", "Research", "Investigacion", "building.research-lab", "icon.research-lab", 60, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.Shipyard] = new(BuildingType.Shipyard, 1, 15, new ConstructionCost(0, 250, 100, 50), BuildingCategory.MilitarySpace, "Astillero", "orbital-production", "Produccion orbital", "Prepara construccion orbital y disponibilidad del astillero.", "Shipyard", "Astillero", "building.shipyard", "icon.shipyard", 70, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.DefenseGrid] = new(BuildingType.DefenseGrid, 1, 10, new ConstructionCost(0, 150, 75, 0), BuildingCategory.Defense, "Malla defensiva", "planetary-fortification", "Fortificacion planetaria", "Fortificacion base para readiness defensivo sin modelar combate activo.", "Defenses", "Defensas", "building.defense-grid", "icon.defense-grid", 80, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.HabitationDistrict] = new(BuildingType.HabitationDistrict, 1, 8, new ConstructionCost(0, 120, 60, 0), BuildingCategory.Civilian, "Distrito habitacional", "population-support", "Soporte poblacional", "Amplia el espacio habitable y la base de crecimiento de colonia.", "PlanetOverview", "Planeta", "building.habitation-district", "icon.habitation-district", 90, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.MedicalCenter] = new(BuildingType.MedicalCenter, 1, 6, new ConstructionCost(0, 160, 120, 20), BuildingCategory.Civilian, "Centro medico", "population-support", "Soporte poblacional", "Aporta soporte sanitario y crecimiento controlado de colonia.", "PlanetOverview", "Planeta", "building.medical-center", "icon.medical-center", 100, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.MilitaryAcademy] = new(BuildingType.MilitaryAcademy, 1, 10, new ConstructionCost(0, 220, 140, 20), BuildingCategory.MilitaryGround, "Academia militar", "ground-readiness", "Preparacion terrestre", "Centro de formacion militar terrestre sin combate activo asociado.", "GroundArmy", "Ejercito Tierra", "building.military-academy", "icon.military-academy", 110, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.Barracks] = new(BuildingType.Barracks, 1, 9, new ConstructionCost(0, 180, 90, 10), BuildingCategory.MilitaryGround, "Barracones", "ground-readiness", "Preparacion terrestre", "Infraestructura base para preparacion de guarnicion y tropas terrestres.", "GroundArmy", "Ejercito Tierra", "building.barracks", "icon.barracks", 120, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.CrewAcademy] = new(BuildingType.CrewAcademy, 1, 10, new ConstructionCost(0, 240, 160, 40), BuildingCategory.MilitarySpace, "Academia de tripulacion", "crew-readiness", "Preparacion de tripulacion", "Aumenta la preparacion de tripulacion para produccion y operaciones orbitales.", "Shipyard", "Astillero", "building.crew-academy", "icon.crew-academy", 130, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.FleetCommandCenter] = new(BuildingType.FleetCommandCenter, 1, 14, new ConstructionCost(0, 320, 220, 60), BuildingCategory.MilitarySpace, "Mando de flota", "fleet-readiness", "Preparacion de flota", "Centro de coordinacion para readiness orbital y control de flota.", "Fleets", "Flotas", "building.fleet-command-center", "icon.fleet-command-center", 140, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes."),
            [BuildingType.LogisticsHub] = new(BuildingType.LogisticsHub, 1, 12, new ConstructionCost(0, 200, 100, 30), BuildingCategory.Logistics, "Centro logistico", "logistics-support", "Soporte logistico", "Coordina soporte logistico para construccion, produccion y expansion futura.", "Logistics", "Logistica", "building.logistics-hub", "icon.logistics-hub", 150, "target-level-x-base-5m", "Duracion base de 5 minutos por nivel objetivo.", "Requiere capacidad libre y recursos suficientes.")
        };

    public static BuildingDefinition Get(BuildingType buildingType) => Definitions[buildingType];
}
