using VoidEmpires.Domain.Buildings;

namespace VoidEmpires.Domain.Assets;

public static class OrbitalAssetCatalog
{
    private static readonly IReadOnlyDictionary<SpaceAssetType, OrbitalAssetDefinition> Definitions =
        new Dictionary<SpaceAssetType, OrbitalAssetDefinition>
        {
            [SpaceAssetType.ScoutCraft] = new(
                SpaceAssetType.ScoutCraft,
                new AssetRequirement(0, 25, BuildingType.Shipyard, 1),
                new ConstructionCost(0, 120, 80, 40),
                0,
                3,
                "Nave exploradora",
                "Exploracion",
                "Exploracion",
                "Reconocimiento",
                "Reconocimiento rapido",
                "Reconocimiento ligero para lectura de rutas y presencia orbital temprana.",
                "Shipyard",
                "Astillero",
                "ship.scout-craft",
                "ship-scout-craft",
                10,
                "PerUnitMinutes",
                "3 minutos por unidad",
                "StockToFleetDevelopmentFlow",
                "Stock local con derivacion a Flotas",
                "Astillero nivel 1 y tripulacion local de 25 operadores.",
                ["Building:Shipyard:1", "OperatorCapacity:25"],
                ["Orbital", "Scout", "Readiness"]),
            [SpaceAssetType.CargoCraft] = new(
                SpaceAssetType.CargoCraft,
                new AssetRequirement(0, 60, BuildingType.Shipyard, 1),
                new ConstructionCost(0, 250, 120, 80),
                1_000,
                2,
                "Nave de carga",
                "Logistica",
                "Logistica",
                "Transporte",
                "Transporte de suministros",
                "Transporte de suministros y soporte logico sin convertir stock en flota activa.",
                "Shipyard",
                "Astillero",
                "ship.cargo-craft",
                "ship-cargo-craft",
                20,
                "PerUnitMinutes",
                "3 minutos por unidad",
                "StockToFleetDevelopmentFlow",
                "Stock local con derivacion a Flotas",
                "Astillero nivel 1 y tripulacion local de 60 operadores.",
                ["Building:Shipyard:1", "OperatorCapacity:60"],
                ["Orbital", "Cargo", "Logistics"]),
            [SpaceAssetType.EscortCraft] = new(
                SpaceAssetType.EscortCraft,
                new AssetRequirement(0, 120, BuildingType.FleetCommandCenter, 1),
                new ConstructionCost(0, 500, 250, 150),
                100,
                4,
                "Nave de escolta",
                "Escolta",
                "Escolta",
                "Cobertura",
                "Cobertura orbital",
                "Cobertura orbital de escolta; esta build solo expone produccion y readiness.",
                "Shipyard",
                "Astillero",
                "ship.escort-craft",
                "ship-escort-craft",
                30,
                "PerUnitMinutes",
                "3 minutos por unidad",
                "StockToFleetDevelopmentFlow",
                "Stock local con derivacion a Flotas",
                "Mando de flota nivel 1 y tripulacion local de 120 operadores.",
                ["Building:FleetCommandCenter:1", "OperatorCapacity:120"],
                ["Orbital", "Escort", "Readiness"]),
            [SpaceAssetType.ColonyCraft] = new(
                SpaceAssetType.ColonyCraft,
                new AssetRequirement(0, 500, BuildingType.LogisticsHub, 2),
                new ConstructionCost(0, 1_500, 800, 500),
                500,
                5,
                "Nave colonial",
                "Colonial",
                "Colonial",
                "Expansion",
                "Expansion y asentamiento",
                "Expansion colonial preparada como catalogo; la ejecucion final sigue fuera de alcance.",
                "Shipyard",
                "Astillero",
                "ship.colony-craft",
                "ship-colony-craft",
                40,
                "PerUnitMinutes",
                "3 minutos por unidad",
                "StockToFleetDevelopmentFlow",
                "Stock local con derivacion a Flotas",
                "Centro logistico nivel 2 y tripulacion local de 500 operadores.",
                ["Building:LogisticsHub:2", "OperatorCapacity:500"],
                ["Orbital", "Colonial", "Expansion"])
        };

    public static OrbitalAssetDefinition Get(SpaceAssetType assetType) => Definitions[assetType];
}
