// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoidEmpires.Infrastructure.Persistence;

#nullable disable

namespace VoidEmpires.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VoidEmpiresDbContext))]
    [Migration("20260601165609_AddCurrentGameplaySchemaCatchup")]
    partial class AddCurrentGameplaySchemaCatchup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Assets.AssetProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlanetaryAssetType")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int?>("SpaceAssetType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.HasIndex("PlanetId", "Sequence")
                        .IsUnique();

                    b.HasIndex("PlanetId", "Status");

                    b.ToTable("AssetProductionOrder");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Assets.OrbitalAssetStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId", "AssetType")
                        .IsUnique();

                    b.ToTable("OrbitalAssetStock");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Assets.PlanetaryAssetStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId", "AssetType")
                        .IsUnique();

                    b.ToTable("PlanetaryAssetStock");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Buildings.PlanetBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<int>("Footprint")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.ToTable("PlanetBuildings");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Buildings.PlanetBuildingCapacity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("BonusCapacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId")
                        .IsUnique();

                    b.ToTable("PlanetBuildingCapacities");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Buildings.PlanetConstructionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId");

                    b.HasIndex("PlanetId", "Sequence")
                        .IsUnique();

                    b.HasIndex("PlanetId", "Status");

                    b.ToTable("PlanetConstructionOrders");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Colonization.PlanetOwnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("civilization_id");

                    b.Property<DateTime>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid")
                        .HasColumnName("planet_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId")
                        .HasDatabaseName("ix_planet_ownerships_civilization_id");

                    b.HasIndex("PlanetId")
                        .IsUnique()
                        .HasDatabaseName("ux_planet_ownerships_planet_id");

                    b.ToTable("planet_ownerships", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Diplomacy.Alliance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAtUtc", "Id");

                    b.ToTable("Alliances");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Diplomacy.AllianceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AllianceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("AllianceId", "CivilizationId")
                        .IsUnique();

                    b.HasIndex("CivilizationId", "JoinedAtUtc", "Id");

                    b.ToTable("AllianceMemberships");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Diplomacy.AlliancePact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PactType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceAllianceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetAllianceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceAllianceId", "TargetAllianceId", "PactType")
                        .IsUnique();

                    b.HasIndex("SourceAllianceId", "Status", "CreatedAtUtc", "Id");

                    b.HasIndex("TargetAllianceId", "Status", "CreatedAtUtc", "Id");

                    b.ToTable("AlliancePacts");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Diplomacy.DiplomaticContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactedCivilizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("ContactedCivilizationId");

                    b.HasIndex("CivilizationId", "ContactedCivilizationId")
                        .IsUnique();

                    b.ToTable("DiplomaticContacts");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Economy.PlanetProductionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CreditsPerHour")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credits_per_hour");

                    b.Property<decimal>("CrystalPerHour")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("crystal_per_hour");

                    b.Property<decimal>("GasPerHour")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gas_per_hour");

                    b.Property<decimal>("MetalPerHour")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("metal_per_hour");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid")
                        .HasColumnName("planet_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId")
                        .IsUnique()
                        .HasDatabaseName("ux_planet_production_profiles_planet_id");

                    b.ToTable("planet_production_profiles", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Economy.PlanetResourceStockpile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Credits")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credits");

                    b.Property<decimal>("Crystal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("crystal");

                    b.Property<decimal>("Gas")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("gas");

                    b.Property<decimal>("Metal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("metal");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid")
                        .HasColumnName("planet_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId")
                        .IsUnique()
                        .HasDatabaseName("ux_planet_resource_stockpiles_planet_id");

                    b.ToTable("planet_resource_stockpiles", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Exploration.ExplorationKnowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceMissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("PlanetId");

                    b.HasIndex("SystemId");

                    b.HasIndex("CivilizationId", "SystemId")
                        .IsUnique()
                        .HasFilter("\"PlanetId\" IS NULL");

                    b.HasIndex("CivilizationId", "SystemId", "PlanetId")
                        .IsUnique()
                        .HasFilter("\"PlanetId\" IS NOT NULL");

                    b.ToTable("ExplorationKnowledge");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Exploration.ExplorationMission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetPlanetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetSystemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("TargetPlanetId");

                    b.HasIndex("TargetSystemId");

                    b.HasIndex("CivilizationId", "Status", "DueAtUtc");

                    b.ToTable("ExplorationMissions");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Fleets.OrbitalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrentPlanetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginPlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("CurrentPlanetId");

                    b.HasIndex("OriginPlanetId");

                    b.HasIndex("CurrentPlanetId", "Status");

                    b.ToTable("OrbitalGroup");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Fleets.OrbitalTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbstractDistanceUnits")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ArrivalAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DepartureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationPlanetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrbitalGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OriginPlanetId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("DestinationPlanetId");

                    b.HasIndex("OrbitalGroupId");

                    b.HasIndex("OriginPlanetId");

                    b.HasIndex("Status", "ArrivalAtUtc");

                    b.ToTable("OrbitalTransfers");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.Galaxy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("galaxies", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.Planet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ColonizationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("colonization_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("OrbitalSlot")
                        .HasColumnType("integer")
                        .HasColumnName("orbital_slot");

                    b.Property<int>("PlanetType")
                        .HasColumnType("integer")
                        .HasColumnName("planet_type");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<Guid>("SolarSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("solar_system_id");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId", "OrbitalSlot")
                        .IsUnique()
                        .HasDatabaseName("ux_planets_solar_system_orbital_slot");

                    b.ToTable("planets", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.SolarSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("integer")
                        .HasColumnName("coordinates_x");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("integer")
                        .HasColumnName("coordinates_y");

                    b.Property<int>("CoordinateZ")
                        .HasColumnType("integer")
                        .HasColumnName("coordinates_z");

                    b.Property<Guid>("GalaxyId")
                        .HasColumnType("uuid")
                        .HasColumnName("galaxy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GalaxyId", "CoordinateX", "CoordinateY", "CoordinateZ")
                        .IsUnique()
                        .HasDatabaseName("ux_solar_systems_galaxy_coordinates");

                    b.ToTable("solar_systems", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.Star", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("SolarSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("solar_system_id");

                    b.Property<int>("StarType")
                        .HasColumnType("integer")
                        .HasColumnName("star_type");

                    b.HasKey("Id");

                    b.HasIndex("SolarSystemId")
                        .IsUnique()
                        .HasDatabaseName("ux_stars_solar_system_id");

                    b.ToTable("stars", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Players.Civilization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Archetype")
                        .HasColumnType("integer")
                        .HasColumnName("archetype");

                    b.Property<Guid?>("HomePlanetId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_planet_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_civilizations_profile_name");

                    b.ToTable("civilizations", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Players.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_player_profiles_user_id");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("VoidEmpires.Domain.Population.PlanetPopulationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BaseCrewCapacity")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseRecruitablePopulation")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlanetId")
                        .HasColumnType("uuid");

                    b.Property<long>("TotalPopulation")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlanetId")
                        .IsUnique();

                    b.ToTable("PlanetPopulationProfiles");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Research.ResearchOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResearchType")
                        .HasColumnType("integer");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourcePlanetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId");

                    b.HasIndex("CivilizationId", "Sequence")
                        .IsUnique();

                    b.HasIndex("CivilizationId", "Status");

                    b.ToTable("ResearchOrders");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Research.ResearchProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CivilizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("ResearchType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CivilizationId", "ResearchType")
                        .IsUnique();

                    b.ToTable("ResearchProjects");
                });

            modelBuilder.Entity("VoidEmpires.Infrastructure.Identity.VoidEmpiresUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VoidEmpires.Infrastructure.Identity.VoidEmpiresUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VoidEmpires.Infrastructure.Identity.VoidEmpiresUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoidEmpires.Infrastructure.Identity.VoidEmpiresUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VoidEmpires.Infrastructure.Identity.VoidEmpiresUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.Planet", b =>
                {
                    b.HasOne("VoidEmpires.Domain.Galaxy.SolarSystem", null)
                        .WithMany("Planets")
                        .HasForeignKey("SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.SolarSystem", b =>
                {
                    b.HasOne("VoidEmpires.Domain.Galaxy.Galaxy", null)
                        .WithMany("SolarSystems")
                        .HasForeignKey("GalaxyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.Star", b =>
                {
                    b.HasOne("VoidEmpires.Domain.Galaxy.SolarSystem", null)
                        .WithOne("Star")
                        .HasForeignKey("VoidEmpires.Domain.Galaxy.Star", "SolarSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoidEmpires.Domain.Players.Civilization", b =>
                {
                    b.HasOne("VoidEmpires.Domain.Players.PlayerProfile", null)
                        .WithMany("Civilizations")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.Galaxy", b =>
                {
                    b.Navigation("SolarSystems");
                });

            modelBuilder.Entity("VoidEmpires.Domain.Galaxy.SolarSystem", b =>
                {
                    b.Navigation("Planets");

                    b.Navigation("Star")
                        .IsRequired();
                });

            modelBuilder.Entity("VoidEmpires.Domain.Players.PlayerProfile", b =>
                {
                    b.Navigation("Civilizations");
                });
#pragma warning restore 612, 618
        }
    }
}
