param(
    [string]$BaseUrl = "http://localhost:5142",
    [string]$Email = "",
    [string]$Password = "",
    [string]$DisplayName = "",
    [string]$CivilizationName = "",
    [string]$HomePlanetName = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
try {
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $OutputEncoding = [System.Text.Encoding]::UTF8
}
catch {
    Write-Verbose "Console UTF-8 encoding setup was not available in this host."
}
. (Join-Path $PSScriptRoot "dev-qa-common.ps1")

function New-DevQaRegistrationSuffix {
    $timestamp = Get-Date -Format "yyyyMMddHHmmss"
    $random = [Guid]::NewGuid().ToString("N").Substring(0, 8)
    return "$timestamp-$random"
}

function Invoke-AccountRegistration {
    param([hashtable]$Body)

    $path = "/api/accounts/register"
    try {
        $result = Invoke-RestMethod `
            -Method Post `
            -Uri ($BaseUrl.TrimEnd("/") + $path) `
            -ContentType "application/json" `
            -Body ($Body | ConvertTo-Json -Depth 8 -Compress)

        return [pscustomobject]@{
            Succeeded = $true
            StatusCode = 201
            Json = $result
            BodyText = $null
        }
    }
    catch {
        $response = $_.Exception.Response
        $statusCode = if ($null -ne $response) { [int]$response.StatusCode } else { $null }
        $responseBody = Get-DevQaHttpResponseBody $_.Exception
        return [pscustomobject]@{
            Succeeded = $false
            StatusCode = $statusCode
            Json = ConvertFrom-DevQaJsonSafely $responseBody
            BodyText = $responseBody
        }
    }
}

$suffix = New-DevQaRegistrationSuffix
$generatedEmail = [string]::IsNullOrWhiteSpace($Email)
$generatedCredential = [string]::IsNullOrWhiteSpace($Password)
$generatedDisplayName = [string]::IsNullOrWhiteSpace($DisplayName)
$generatedCivilizationName = [string]::IsNullOrWhiteSpace($CivilizationName)

$safeEmail = if ($generatedEmail) { "qa-$suffix@example.test" } else { $Email.Trim() }
$localCredential = if ($generatedCredential) { "Tmp!7$suffix" } else { $Password }
$safeDisplayName = if ($generatedDisplayName) { "QA Commander $suffix" } else { $DisplayName.Trim() }
$safeCivilizationName = if ($generatedCivilizationName) { "QA Civilization $suffix" } else { $CivilizationName.Trim() }
$safeHomePlanetName = $HomePlanetName.Trim()

$payload = [ordered]@{
    email = $safeEmail
    displayName = $safeDisplayName
    civilizationName = $safeCivilizationName
}
$payload["password"] = $localCredential
$payload["confirmPassword"] = $localCredential

if (-not [string]::IsNullOrWhiteSpace($safeHomePlanetName)) {
    $payload.homePlanetName = $safeHomePlanetName
}

Write-Warning "Esta script registra un usuario local de QA contra la base configurada en el backend. No la uses con credenciales reales."
Write-Host ""
Write-Host "Target"
Write-Host "BaseUrl: $BaseUrl"
Write-Host "Endpoint: POST /api/accounts/register"
Write-Host "Email: $(if ($generatedEmail) { $safeEmail } else { '(supplied email not echoed)' })"
Write-Host "DisplayName: $safeDisplayName"
Write-Host "CivilizationName: $safeCivilizationName"
if (-not [string]::IsNullOrWhiteSpace($safeHomePlanetName)) {
    Write-Host "HomePlanetName: $safeHomePlanetName"
}

$result = Invoke-AccountRegistration $payload
if (-not $result.Succeeded -or -not $result.Json.succeeded) {
    $errors = Get-DevQaResponseErrorText -ResponseObject $result.Json -FallbackText $result.BodyText
    $details = if (-not [string]::IsNullOrWhiteSpace($errors)) { $errors } else { $result.BodyText }
    if ([string]::IsNullOrWhiteSpace($details)) {
        $details = "No response body was returned."
    }

    throw "Registration failed with HTTP $($result.StatusCode). $details"
}

$created = $result.Json

Write-Host ""
Write-Host "Registration created a local account world."
[pscustomobject]@{
    UserId = $created.userId
    PlayerProfileId = $created.playerProfileId
    CivilizationId = $created.civilizationId
    HomePlanetId = $created.homePlanetId
    HomePlanetName = $created.homePlanetName
    NextRoute = $created.nextRoute
    StartingResources = (Format-DevQaResourceSummary $created.startingResources).Summary
} | Format-List

if ($generatedCredential) {
    Write-Host ""
    Write-Host "Local temporary password generated by this script:"
    Write-Host $localCredential
    Write-Host "Use it only for this local QA account. It is not stored by this script."
}
else {
    Write-Host ""
    Write-Host "Password: supplied by caller and intentionally not printed."
}

Write-Host ""
Write-Host "Next frontend route:"
Write-Host $created.nextRoute
Write-Host ""
Write-Host "Nota operativa: esta script llama solo al endpoint normal de registro, no aplica seeds, no ejecuta migraciones, no borra datos y no imprime contrasenas suministradas."
